"""empty message

Revision ID: 4df059c5eab7
Revises: dc2c818b945f
Create Date: 2025-07-30 14:50:51.974289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df059c5eab7'
down_revision: Union[str, Sequence[str], None] = 'dc2c818b945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'default_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'default_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
